#  -*- coding: utf-8 -*-
import uuid
import psycopg2

uuid = str(uuid.uuid4())

conn = psycopg2.connect(database="NPrinting", user="qlik",password="Aa12345678", host="10.122.36.129", port="5432")
cursor = conn.cursor()
##设置目标表
table = (
        # 'public."AppObjectTags"',
        'public."AnalyticConnections"',
        'public."AppSeedInfoes"',
        'public."AppDataSegments"',
        'public."AppInternals"',
        'public."AppObjects"',
        'public."AppStatus"',
        'public."BinaryDeletes"',
        'public."BinaryDeleteProperties"',
        'public."BinaryDownloads"',
        'public."BinaryDownloadProperties"',
        'public."AppContentQuotas"',
        'public."Apps"',
        'public."AppContents"',
        'public."BinarySyncRuleEvaluations"',
        'public."CompositeEventRuleOperationals"',
        'public."CompositeEventRules"',
        'public."CompositeEventOperationals"',
        'public."CompositeEventTimeConstraints"',
        'public."ContentLibraries"',
        'public."CustomPropertyDefinitions"',
        'public."CompositeEvents"',
        # 'public."ContentLibraryStaticContentReferences"',
        'public."ExternalProgramTasks"',
        'public."EngineServices"',
        'public."ExecutionSessions"',
        # 'public."ExtensionStaticContentReferences"',
        'public."Extensions"',
        # 'public."DataConnectionTags"',
        # 'public."ExtensionTags"',
        'public."ExecutionResults"',
        'public."ExecutionResultDetails"',
        'public."EngineServiceSettings"',
        'public."DataConnections"',
        'public."CustomPropertyValues"',
        'public."ExternalProgramTaskOperationals"',
        # 'public."ExecutionResultDetailExecutionResults"',
        'public."FileReferences"',
        'public."FileExtensionWhiteLists"',
        # 'public."FileExtensionFileExtensionWhiteLists"',
        # 'public."FileReferenceStaticContentReferences"',
        'public."FileExtensions"',
        'public."LicenseAnalyzerAccessGroups"',
        'public."LicenseAnalyzerAccessTypes"',
        'public."LicenseAnalyzerTimeAccessUsageSessions"',
        'public."LicenseLoginAccessTypes"',
        'public."LicenseLoginAccessUsages"',
        'public."LicenseProfessionalAccessTypes"',
        'public."LicenseUserAccessUsages"',
        'public."LicenseProfessionalAccessUsages"',
        'public."LicenseProfessionalAccessGroups"',
        'public."LicenseUserAccessTypes"',
        'public."LicenseUserAccessGroups"',
        'public."LicenseLoginAccessUsageSessions"',
        'public."LicenseAnalyzerAccessUsages"',
        'public."LicenseAnalyzerTimeAccessTypes"',
        'public."Licenses"',
        'public."LicenseAnalyzerTimeAccessUsages"',
        # 'public."OdagModelGroupOdagLinks"',
        'public."Locks"',
        'public."PrintingServiceSettings"',
        'public."MqChangeNotificationRegistrations"',
        'public."OdagLinkUsages"',
        'public."OdagModelGroups"',
        'public."OdagLinks"',
        'public."OdagRequests"',
        'public."OdagServices"',
        # 'public."PrintingServiceTags"',
        'public."OdagEngineGroups"',
        'public."OdagServiceSettings"',
        'public."PrintingServices"',
        'public."MimeTypes"',
        'public."PrintingServiceSettingsLogVerbosities"',
        'public."ProxyServiceSettingsLogVerbosities"',
        'public."ReloadTaskOperationals"',
        # 'public."ProxyServiceTags"',
        'public."ReloadTasks"',
        'public."RepositoryServiceSettingsSynchronizations"',
        'public."RepositoryServiceSettingsExternalCerts"',
        'public."ProxyServiceSettings"',
        'public."RemovedSystemRules"',
        'public."RepositoryServiceSettingsCleaningAgents"',
        # 'public."RepositoryServiceTags"',
        'public."ProxyServices"',
        # 'public."ReloadTaskSystemNotifications"',
        'public."ProxyServiceCertificates"',
        'public."RepositoryServiceSettings"',
        'public."RepositoryServiceSettingsLogVerbosities"',
        'public."ServerNodeHeartbeats"',
        'public."ServerNodeRoles"',
        'public."ServiceClusterSettingsEncryptions"',
        'public."SchedulerServices"',
        'public."ServiceClusterSettings"',
        'public."Selections"',
        'public."SchemaEventOperationals"',
        'public."SchemaEvents"',
        # 'public."ServerNodeRoleServerNodeConfigurations"',
        'public."SchedulerServiceSettings"',
        'public."ServiceClusterSettingsDbCredentials"',
        'public."RepositoryServices"',
        'public."SelectionItems"',
        'public."ServerNodeConfigurations"',
        'public."SchedulerServiceSettingsLogVerbosities"',
        'public."SyncSessions"',
        'public."ServiceStatus"',
        'public."SharedContentMetaDatas"',
        'public."SystemNotifications"',
        # 'public."SharedContentTags"',
        'public."TableDefinitionColumns"',
        # 'public."StreamTags"',
        'public."Streams"',
        'public."SharedContents"',
        'public."SystemRules"',
        # 'public."StaticContentReferenceAppContents"',
        # 'public."SystemNotificationUsers"',
        'public."SystemInfoes"',
        'public."ServiceClusters"',
        'public."StaticContentReferences"',
        'public."ServiceClusterSettingsSharedPersistenceProperties"',
        # 'public."SystemRuleTags"',
        # 'public."SharedContentStaticContentReferences"',
        'public."UserSyncTasks"',
        # 'public."TagApps"',
        # 'public."TagContentLibraries"',
        # 'public."TagUsers"',
        # 'public."Tags"',
        'public."UserSyncTaskOperationals"',
        # 'public."TagSchedulerServices"',
        'public."TableDefinitions"',
        'public."TableDefinitionListColumns"',
        'public."TempContents"',
        'public."TermsAcceptances"',
        # 'public."TagExternalProgramTasks"',
        'public."UserAttributes"',
        'public."UserDirectories"',
        # 'public."UserDirectoryTags"',
        # 'public."UserSyncTaskTags"',
        # 'public."TagReloadTasks"',
        # 'public."TagServerNodeConfigurations"',
        # 'public."TagEngineServices"',
        'public."UserDirectorySettings"',
        'public."Widgets"',
        # 'public."WidgetTags"',
        'public."WebExtensionLibraries"',
        # 'public."VirtualProxyConfigTags"',
        'public."Users"',
        'public."VirtualProxyConfigs"',
        'public."VirtualProxyConfigJwtAttributeMapItems"',
        # 'public."WebExtensionLibraryTags"',
        'public."VirtualProxyConfigSamlAttributeMapItems"',
        # 'public."VirtualProxyConfigProxyServiceSettings"',
        'public."WebExtensionTypes"',
        # 'public."__MigrationHistory"',
        # 'public."_deletedentitylog"',
        # 'public."_locktable"',
        # 'public."_migrationlog"',
        'public."backup_systemrules"'
        )
for tab in table:
    cursor.execute("select "+'"'+"ID"+'"'+" from "+tab+";")

    rows = cursor.fetchall() #获取全部数据
    # rows = cursor.fetchmany(size=100) #batch为100条数据进行获取

    for i in rows:
        row = str(i).replace('(', '').replace(')', '').replace(',', '')
        # print(row)
        update_sql = "UPDATE "+tab+" \
                            SET "+'"'+"ModifiedByUserName"+'" = '+row+'  \
                            WHERE '+'"'+"ID"+'" ='+row+";"
        print(update_sql)
        cursor.execute(update_sql)
        conn.commit()

        # cursor.execute("select * from "+table+"  \
        #             WHERE "+'"'+"ID"+'" ='+row+";")
        # select_sql = cursor.fetchall()
        # print(select_sql)

cursor.close()
conn.close()

print("--- Update execution complete! ---")