    cam_srv_ww.fact_iaas_tcv_tracking_report [opportunity_id]
>> cam_srv_ww.fact_iaas_tcv_tracking_report [opportunity_no]
    cam_srv_ww.fact_iaas_tcv_tracking_report [contract_id]
    cam_srv_ww.fact_iaas_tcv_tracking_report [contract_ln_no]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_transaction_no]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_transaction_ln_no]
    cam_srv_ww.fact_iaas_tcv_tracking_report [billing_no]
    cam_srv_ww.fact_iaas_tcv_tracking_report [billing_item_no]
    cam_srv_ww.fact_iaas_tcv_tracking_report [subs_contract_no]
    cam_srv_ww.fact_iaas_tcv_tracking_report [subs_contract_item_no]
    cam_srv_ww.fact_iaas_tcv_tracking_report [subs_billing_no]
    cam_srv_ww.fact_iaas_tcv_tracking_report [subs_billing_item_no]
    cam_srv_ww.fact_iaas_tcv_tracking_report [opportunity_type]
    cam_srv_ww.fact_iaas_tcv_tracking_report [opportunity_svc_mdl]
>> cam_srv_ww.fact_iaas_tcv_tracking_report [opportunity_nm]
    cam_srv_ww.fact_iaas_tcv_tracking_report [opportunity_owner]
>> cam_srv_ww.fact_iaas_tcv_tracking_report [iaas_pursuit_lead]
>> cam_srv_ww.fact_iaas_tcv_tracking_report [opportunity_end_cust_id]
    cam_srv_ww.fact_iaas_tcv_tracking_report [truscale_new_cust_flg]
    cam_srv_ww.fact_iaas_tcv_tracking_report [contract_quote_type_cd]
    cam_srv_ww.fact_iaas_tcv_tracking_report [contract_eaas_catg_cd]
    cam_srv_ww.fact_iaas_tcv_tracking_report [contract_desc]
    cam_srv_ww.fact_iaas_tcv_tracking_report [contract_status]
    cam_srv_ww.fact_iaas_tcv_tracking_report [lenovo_sales_orgnization_cd]
    cam_srv_ww.fact_iaas_tcv_tracking_report [master_contract_no]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_curr_cd]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_acnt_id]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_lease_type_cd]
>> cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_term_duration]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_product_no]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_charge_type_cd]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_nodes_qty]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_proposed_dt]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_agreement_dt]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_ttl_contract_value]
>> cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_ttl_contract_value_usd]
>> cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_minimum_contract_value_usd]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_minimum_contract_value_curr_cd]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_avg_margin]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_minimum_margin]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_one_time_charge_amt_usd]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_one_time_charge_curr_cd]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_mthly_per_node_avg_amt_usd]
    cam_srv_ww.fact_iaas_tcv_tracking_report [sales_contract_mthly_per_node_minimum_amt_usd]
    cam_srv_ww.fact_iaas_tcv_tracking_report [running_iaas_flg]
    cam_srv_ww.fact_iaas_tcv_tracking_report [subsription_billing_source_transaction_type]
    cam_srv_ww.fact_iaas_tcv_tracking_report [billing_product_no]
>> cam_srv_ww.fact_iaas_tcv_tracking_report [billing_created_dttm]
    cam_srv_ww.fact_iaas_tcv_tracking_report [billing_start_dt]
    cam_srv_ww.fact_iaas_tcv_tracking_report [billing_end_dt]
    cam_srv_ww.fact_iaas_tcv_tracking_report [mthly_invoiced_curr_amt]
    cam_srv_ww.fact_iaas_tcv_tracking_report [mthly_invoiced_usd_amt]
    cam_srv_ww.fact_iaas_tcv_tracking_report [one_time_invoiced_curr_amt]
    cam_srv_ww.fact_iaas_tcv_tracking_report [one_time_invoiced_usd_amt]
    cam_srv_ww.fact_iaas_tcv_tracking_report [dw_source_id]
    cam_srv_ww.fact_iaas_tcv_tracking_report [dw_update_dt]
    cam_srv_ww.fact_iaas_tcv_tracking_report [dw_insert_dt]

>> cam_srv_ww.dim_svc_country [country_nm]
    cam_srv_ww.dim_svc_country [region_cd]
    cam_srv_ww.dim_svc_country [region_nm]
>> cam_srv_ww.dim_svc_country [geo_cd]
    cam_srv_ww.dim_svc_country [dw_insert_dt]
    cam_srv_ww.dim_svc_country [dw_update_dt]
    cam_srv_ww.dim_svc_country [dw_source_id]

    cam_corp.dim_lenovo_sales_org_vw [lenovo_sales_org_nm]
    cam_corp.dim_lenovo_sales_org_vw [company_cd]
    cam_corp.dim_lenovo_sales_org_vw [dw_source_id]
    cam_corp.dim_lenovo_sales_org_vw [dw_insert_dt]
    cam_corp.dim_lenovo_sales_org_vw [dw_update_dt]

>> cam_cus.dim_acnt [acnt_nm]
    cam_cus.dim_acnt [country_cd]
    cam_cus.dim_acnt [region_cd]
    cam_cus.dim_acnt [dw_source_id]
    cam_cus.dim_acnt [dw_insert_dt]
    cam_cus.dim_acnt [dw_update_dt]

    cam_ms.dim_sales_product_category [product_no]
>> cam_ms.dim_sales_product_category [product_nm]
    cam_ms.dim_sales_product_category [product_category_bu]
    cam_ms.dim_sales_product_category [product_catg_lvl_1_cd]
    cam_ms.dim_sales_product_category [product_catg_lvl_1_desc]
    cam_ms.dim_sales_product_category [product_catg_lvl_2_cd]
    cam_ms.dim_sales_product_category [product_catg_lvl_2_desc]
    cam_ms.dim_sales_product_category [product_catg_lvl_3_cd]
    cam_ms.dim_sales_product_category [product_catg_lvl_3_desc]
    cam_ms.dim_sales_product_category [product_catg_lvl_4_cd]
    cam_ms.dim_sales_product_category [product_catg_lvl_4_desc]
    cam_ms.dim_sales_product_category [product_catg_lvl_5_cd]
    cam_ms.dim_sales_product_category [product_catg_lvl_5_desc]
    cam_ms.dim_sales_product_category [dw_source_id]
    cam_ms.dim_sales_product_category [dw_insert_dt]
    cam_ms.dim_sales_product_category [dw_update_dt]
    cam_ms.dim_sales_product_category [dw_del_flg]
